#游戏世界匹配系统BATE1
mainServer: true

motd: "lobby"
pingDelay: 3000
timeOut: 200

Group:
  Bedwars:
    name: "起床战争"
    command: "qc"
    sub:
      tsqc:
        name: "特色"
        command: "tsqc"
        servers:
          - "BW-OneXP-1"
          - "BW-OneXP-2"
          - "BW-OneXP-3"
          - "BW-OneXP-4"
          - "BW-OneXP-5"
          - "BW-OneXP-6"
          - "BW-OneXP-7"
          - "BW-OneXP-8"
      jdqc:
        name: "经典"
        command: "jdqc"
        servers:
          - "BW-XP-1"
          - "BW-XP-2"
          - "BW-XP-3"
          - "BW-XP-4"
          - "BW-XP-5"
          - "BW-XP-6"
          - "BW-XP-7"
          - "BW-XP-8"
          - "BW-XP-9"
          - "BW-XP-10"
          - "BW-XP-11"
          - "BW-XP-12"
          - "BW-XP-13"
          - "BW-XP-14"
          - "BW-XP-15"
          - "BW-XP-16"
          - "BW-XP-17"
          - "BW-XP-18"
          - "BW-XP-19"
          - "BW-XP-20"
          - "BW-XP-21"
          - "BW-XP-22"
          - "BW-XP-23"
          - "BW-XP-24"
          - "BW-XP-25"
          - "BW-XP-26"
          - "BW-XP-27"
      x:
        name: "新版"
        command: "x"
        servers:
          - "BW-X-1"
          - "BW-X-2"
          - "BW-X-3"
          - "BW-X-4"
          - "BW-X-5"
          - "BW-X-6"
          - "BW-X-7"
          - "BW-X-8"
          - "BW-X-9"
          - "BW-X-10"
          - "BW-X-11"
          - "BW-X-12"
          - "BW-X-13"
          - "BW-X-14"
          - "BW-X-15"
          - "BW-X-16"
          - "BW-X-17"
          - "BW-X-18"
          - "BW-X-19"
          - "BW-X-20"
          - "BW-X-21"
          - "BW-X-22"
          - "BW-X-23"
          - "BW-X-24"
          - "BW-X-25"
          - "BW-X-26"
          - "BW-X-27"
          - "BW-X-28"